name: "Deploy"
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NIXPKGS_ALLOW_UNFREE: 1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Install nix dependencies
        run: nix-shell --command "echo Hello World"

      - name: Install npm dependencies
        run: nix-shell --command "npm install"
      
      - name: Build develop
        if: github.ref == 'refs/heads/develop'
        run: nix-shell --command "npm run gulp build"
        env:
          HUGO_BASEURL: https://develop-build--sransara-com.netlify.app/

      - name: Deploy develop
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: develop-build
          publish_dir: ./public
        
      - name: Pulling develop into master
        if: github.ref == 'refs/heads/develop'
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: master
          pr_title: Pulling develop into master

      - name: Build master
        if: github.ref == 'refs/heads/master'
        run: nix-shell --command "npm run gulp build"
        
      - name: Deploy master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master-build
          publish_dir: ./public
